name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  schedule:
  - cron: 0 0 * * 1

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Prep binaries
        run: |
          docker pull dkhamsing/awesome_bot:1.20.0
      - name: awesome_bot links check
        run: |
          AWESOME_BOT="docker run -i --rm -v $(pwd):$(pwd):rw -w $(pwd) dkhamsing/awesome_bot:1.20.0"
          $AWESOME_BOT --version
          $AWESOME_BOT README.md --allow-ssl --white-list awesome.re,https://drive.google.com/file/d/1VWwgp0pWy6pANO-i7LBSFJr-U1khhQWp/view
